name: ""
description: ""

url: "//ycpcs.github.io/cs360-spring2019"

markdown: kramdown
kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge